CREATE DATABASE Optus;

USE Optus;

-- USUARIO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,

	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Permissao VARCHAR(100) NOT NULL
);

-- ARTISTA

CREATE TABLE Artista(
	IdArtista INT PRIMARY KEY IDENTITY NOT NULL,

	Nome VARCHAR(100) NOT NULL
);

-- Albuns

CREATE TABLE Album(
	IdAlbum INT PRIMARY KEY IDENTITY NOT NULL,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),

	Nome VARCHAR(100) NOT NULL,
	DataLancamento VARCHAR(100) NOT NULL
);

-- Estilos

CREATE TABLE Estilos(
	IdEstilo INT PRIMARY KEY IDENTITY NOT NULL,

	Descricao VARCHAR(100) NOT NULL
);

CREATE TABLE AlbumEstilo(
	-- LIGA O ESTILO AO ALBUM
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo)
);