CREATE DATABASE Pets;

USE Pets;

-- CLINICA e VET

CREATE TABLE Clinica(
	IdClinica INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Endereco VARCHAR(100) NOT NULL
);

CREATE TABLE Veterinario(
	IdVet INT PRIMARY KEY IDENTITY NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),

	Nome VARCHAR(100) NOT NULL,
	CRV VARCHAR(100) NOT NULL
)

--PETS E CARACTERISTICAS

CREATE TABLE DONO(
	IdDono INT PRIMARY KEY IDENTITY NOT NULL,

	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL
);

CREATE TABLE TipoPet(
	IdTipoPet INT PRIMARY KEY IDENTITY NOT NULL,

	Descricao VARCHAR(100) NOT NULL
);

CREATE TABLE Raca(
	IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),

	Descricao VARCHAR(100) NOT NULL
);



CREATE TABLE Pet(
	IdPet INT PRIMARY KEY IDENTITY NOT NULL,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),

	Nome VARCHAR(100) NOT NULL,
	DataNascimento VARCHAR(100) NOT NULL
)

-- Atendimento

CREATE TABLE Atendimento(
	IdAtendimento INT PRIMARY KEY IDENTITY NOT NULL,
	IdVet INT FOREIGN KEY REFERENCES Veterinario(IdVet),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),

	Descricao VARCHAR(100) NOT NULL,
	Horario VARCHAR(100) NOT NULL
)